# Release a new version of the image
name: Release
run-name: ${{ github.actor }} released ${{ github.ref }}
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY_HOST }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          push: true
          tags: ${{ vars.DOCKER_REGISTRY_HOST }}/jwt-keys-rotator:latest,${{ vars.DOCKER_REGISTRY_HOST }}/jwt-keys-rotator:${{ github.ref }}

      - name: Inspect
        run: |
          docker buildx imagetools inspect ${{ vars.DOCKER_REGISTRY_HOST }}/jwt-keys-rotator:latest
